site_name: Wind turbine and wind farm noise propagation
site_url: ""
use_directory_urls: false


plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            relative_crossrefs: true
            members_order: source
            docstring_section_style: list
            heading_level: 3
            merge_init_into_class: true
            # show_bases: false
            # show_if_no_docstring: false
            show_root_full_path: False
            show_root_heading: true
            # show_source: false
            # show_submodules: false
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


theme:
  name: "material"
  # features:
  #   - search.share
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

  palette:
    - scheme: slate
      toggle: 
        icon: material/weather-sunny
        name: Dark mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
  #user_color_mode_toggle: true
# markdown_extensions:
#   - markdown_fortran.wrap:
#       base_path: docs
#       encoding: 'utf-8'

nav:
  - Overview: index.md

  - Installation: installation.md

  - WAPE: WAPE.md 

  - Python tools for Pre-Post processing:
    - Les: reference/les.md
    - Source Model:
      - Wind_turbine: reference/source/wind_turbine.md
      - Mesh: reference/source/mesh.md
      - Main: reference/source/main.md
      - Function: reference/source/function.md
      - Parallel: reference/source/parallel.md
      - Wp_goody: reference/source/WP_Goody.md
      - Wp_lee: reference/source/WP_LEE.md
      - Utils: reference/source/utils.md
      - Fresnelcs: reference/source/fresnelCS.md
      - Bem: reference/source/BEM.md
      - Func_repo_xfoil: reference/source/func_repo_XFOIL.md
      - Mio: reference/source/mio.md
      - Atmos: reference/source/atmos.md
    - Pre: reference/pre.md
    - Post processing:
      - wape: reference/wape.md
      - Gtpe: reference/gtpe.md
      - Deltalfield: reference/deltaLfield.md
      - Combine: reference/combine.md
      - Spl: reference/spl.md
      - Spl_process: reference/spl_process.md
    - Utils: reference/utils.md
    - Auralization tool box:
      - Audio_tools: reference/audio_tools.md
      - Auralization: reference/auralization.md

  - Examples:
    - Source model: 
        - General: examples/source.md
        - Simple input: examples/simple_input.md
        - LES input: examples/les_input.md
        # - Multiple turbines: examples/multiple_turbines.md
    - WAPE simulation: 
        - General: examples/propagation.md
        - One wind turbine: examples/propa_1_turbine.md
        - Multiple turbines: examples/propa_2_turbines.md
    - Complete windfarm simulation: examples/complete_simulation.md

