# name: Deploy MkDocs Documentation
#
# on:
#   push:
#     branches:
#       - main # Trigger workflow on push to the main
#
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#
#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.x"
#
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements_for_site.txt
#
#       # - name: Generate API Reference Documentation
#       #   run: |
#       #     python docs/scripts/gen_ref_pages.py
#       #     echo "Generated reference documentation."
#
#       - name: Build MkDocs site
#         run: mkdocs build # Generates the static site in the ./site folder
#
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.TOKEN }}
#           publish_dir: ./site
name: deploy mkdocs


on:
  push:
    branches:
      - master 


      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r requirements_for_site.txt 


      - run: mkdocs gh-deploy --force
